services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    image: ordo_image
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    depends_on:
      - db

  test:
    build:
      context: .
      target: test
    image: ordo_image_test
    env_file:
      - .env
    depends_on:
      - db
    command: ['npm', 'run', 'test']

volumes:
  pgdata:
