services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    image: lesholikov/ordo_api:${IMAGE_TAG:-latest}
    ports:
      - '${PORT}:3000'
    env_file:
      - .env
    depends_on:
      - db

volumes:
  pgdata:
